DROP DATABASE IF EXISTS hw5;
CREATE DATABASE hw5;
USE hw5;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	age INT
);

INSERT INTO `users` VALUES ('1',20),
('2',25),
('3',30),
('4',40),
('5',50);

SELECT AVG(age) FROM users;